version: '3'
services:

  massa-core:
    image: peterjah/massa-core
    container_name: massa-core
    restart: always
    environment:
      - DISCORD=${DISCORD_ID}
      - WALLETPWD=${WALLETPWD}
    ports:
      - "31244:31244"
      - "31245:31245"
      - "33035:33035"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
      - ./massa_mount:/massa_mount

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --stop-timeout 360s --interval 360 massa-core

volumes:
  massa-core:
