// Code generated by "stringer -type=NodeStatus"; DO NOT EDIT.

package node_manager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Up-1]
	_ = x[Down-2]
	_ = x[Installing-3]
}

const _NodeStatus_name = "UnknownUpDownInstalling"

var _NodeStatus_index = [...]uint8{0, 7, 9, 13, 23}

func (i NodeStatus) String() string {
	if i < 0 || i >= NodeStatus(len(_NodeStatus_index)-1) {
		return "NodeStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeStatus_name[_NodeStatus_index[i]:_NodeStatus_index[i+1]]
}
