---
- hosts: all
  become: true
  tasks:
    - name: Uninstall old versions of docker
      apt:
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker and docker-compose 
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Ensure docker deamon is running
      service:
        name: docker
        state: started

    - name: Copy docker compose file
      copy:
        src: ./docker-compose.yml
        dest: /home/docker-compose.yml

    - name: Fill and copy env file
      ansible.builtin.template:
        src: ./template.env
        dest: /home/.env

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/massa_mount
        state: directory

    - name: Pull docker image
      community.docker.docker_compose:
        project_src: /home
        pull: true
        state: present

    - name: Enable logrotate for docker containers
      copy: src=docker-container-logrotate dest=/etc/logrotate.d/docker-container-logrotate
